### ISSUE TITLE
About KSU

### ISSUE THREAD

**Issue by azwhikaru** [notcbw/2019_android_walkman#6]
hi, what version of Kernel SU are you using in this repository? have you made any patches on the code or defconfig? i tried to build with the latest of Kernel SU with sony's default defconfig, but the manager reported that non-GKI devices are not supported. however using your code and your prebuilt boot.img will work fine

**Comment by notcbw** [comment]
You can see the exact commit of the KSU that I was using. I have changed some code from KSU to make it work. I think I have included a patch somewhere.
